#!/opt/nodejs/bin/node

const fs = require('fs')
const split = require('split')
console.log("START open-runtime-nodejs")

// Open named pipes
const inFd = fs.openSync('/tmp/runtime-input', 'r')
const outFd = fs.openSync('/tmp/runtime-output', 'w')

fs.createReadStream(null, {fd: inFd})
    .pipe(split())
    .on('data', processEvent)

module.paths.push(process.cwd())
const [module_name, func_name] = process.argv[2].split('.')
const package = require(module_name)
const handler = package[func_name]

function processEvent (event) {
  if (!event)
    return
  console.log(`EVENT open-runtime-nodejs: ${JSON.stringify(event)}`)
  const parsedEvent = JSON.parse(event)
  const result = handler(event)

  fs.writeSync(outFd, `${JSON.stringify(result)}\n`)
}

