#!/opt/nodejs/bin/node

//require('/opt/nodejs')
const split = require('split')
console.error("START open-runtime-nodejs")

process.stdin.pipe(split()).on('data', processEvent)

module.paths.push(process.cwd())
const [module_name, func_name] = process.argv[2].split('.')
const package = require(module_name)
const handler = package[func_name]

function processEvent (event) {
  if (!event)
    return
  console.error(`EVENT open-runtime-nodejs: ${JSON.stringify(event)}`)
  const parsedEvent = JSON.parse(event)
  const result = handler(event)
  console.error(JSON.stringify(result))

  console.log(`${JSON.stringify(result)}`)
}

